export const PRIMARY_TRACK_COLOR = 'red';
export const PRIMARY_TRACK_ARROW_COLOR = '#FF4040C0';
export const PRIMARY_TRACK_COLOR_DONE = '#FF000080';
export const SECONDARY_TRACK_COLOR = 'blue';
export const SECONDARY_TRACK_ARROW_COLOR = '#0000C0C0';
export const HIGHLIGHTED_TRACK_COLOR = '#4040FF';
export const SELECTED_TRACK_SECTION_COLOR = '#E0E000C0';
