name: trailence-e2e

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=trailence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  smtp:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  back:
    depends_on:
      db:
        condition: service_healthy
      smtp:
        condition: service_started
    image: trailence/back:${TRAILENCE_BACK_VERSION}
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DB=trailence
      - TRAILENCE_JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=smtp
      - SMTP_PORT=1025
      - SMTP_AUTH_ENABLED=false
      - SMTP_TLS_ENABLED=false
      - TRAILENCE_INIT_USER=${TRAILENCE_INIT_USER}
      - TRAILENCE_INIT_PASSWORD=${TRAILENCE_INIT_PASSWORD}
  front:
    build:
      context: ./docker
    depends_on:
      - back
    ports:
      - 80:80
    volumes:
      - ../../www:/usr/share/nginx/html/:ro
    environment:
      - TRAILENCE_BACK_NAME=back
      - TRAILENCE_BACK_PORT=8080
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 60s
