name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @angular/cli cpy-cli rimraf
          npm ci
      - name: Build Production
        run: npm run build -- --configuration=production
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build Android
        run: |
          ionic capacitor sync android --configuration=android-prod
          rimraf android/app/src/main/assets/public/assets/apk
          cd android/environments/prod
          cpy . ../..
          cd ../../..
          cd android
          echo "ext { jkspass = '' }" > keys.gradle
          chmod 777 ./gradlew
          ./gradlew assembleDebug
      - name: Tests
        run: npm run test -- --configuration=ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
