name: Build
on: [push, pull_request]
jobs:
  build-web-app:
    name: Build - Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @angular/cli cpy-cli rimraf
          npm ci
      - name: Build Production
        run: npm run build -- --configuration=production
  build-android:
    name: Build - Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @angular/cli cpy-cli rimraf
          npm ci
      - name: Build Android
        run: |
          ionic capacitor sync android --configuration=android-prod
          rimraf android/app/src/main/assets/public/assets/apk
          cd android/environments/prod
          cpy . ../..
          cd ../../..
          cd android
          echo "ext { jkspass = '' }" > keys.gradle
          chmod 777 ./gradlew
          ./gradlew assembleDebug
  unit-tests-web-app:
    name: Unit Tests - Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @angular/cli cpy-cli rimraf
          npm ci
      - name: Unit Tests
        run: npm run test -- --configuration=ci
      - name: Store coverage results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-web-app-coverage-report
          path: ./coverage/app/lcov.info
          if-no-files-found: error
          retention-days: 5
  e2e-tests-web-app:
    name: E2E Tests - Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @angular/cli cpy-cli rimraf mkdirp
          npm ci
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            trailence/front
          tags: |
            type=ref,prefix=snapshot-,event=branch
            type=ref,event=tag
      - name: Instrument
        run: |
          npm run build -- --configuration=development
          npm run instrument
          mkdir .nyc_output
      - name: Tests End 2 End
        id: e2e
        run: |
          cd e2e/github
          chmod 777 ./run.sh
          ./run.sh
      - name: Build coverage report
        run: |
          ls -l .nyc_output
          npm run coverage-report
          ls -l coverage/e2e
          sed -i -e 's!www/webpack:/!!' coverage/e2e/lcov.info
          ls -l coverage/e2e
      - name: Upload failure screenshot
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: wdio_error_${{github.run_number}}.png
          path: e2e/wdio_error.png
          retention-days: 5
      - name: Store coverage results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-web-app-coverage-report
          path: ./coverage/e2e/lcov.info
          if-no-files-found: error
          retention-days: 5
  sonar:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    needs:
      - unit-tests-web-app
      - e2e-tests-web-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Retrieve web app unit tests coverage results
        uses: actions/download-artifact@v4
        with:
          name: unit-tests-web-app-coverage-report
          path: coverage/app
      - name: Retrieve web app e2e tests coverage results
        uses: actions/download-artifact@v4
        with:
          name: e2e-tests-web-app-coverage-report
          path: coverage/e2e
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ env.SONAR_TOKEN != '' }}
